### ISSUE TITLE
Ococo man install procedure breaks Conda

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/ococo#23]
```
`$ /Users/karel/miniconda3/bin/conda create -y --name dymas -c bioconda python==3.4 snakemake==3.4.2 samtools git cmake gnuplot ococo numpy biopython pysam==0.8.4 edlib`




    Traceback (most recent call last):
      File "/Users/karel/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/karel/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/karel/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/Users/karel/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/karel/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/karel/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/Users/karel/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "/Users/karel/miniconda3/lib/python3.5/site-packages/conda/install.py", line 960, in link
        os.makedirs(dst_dir)
      File "/Users/karel/miniconda3/lib/python3.5/os.py", line 241, in makedirs
        mkdir(name, mode)
    FileExistsError: [Errno 17] File exists: '/Users/karel/miniconda3/envs/dymas/share/man/man1'
```

**Comment by karel-brinda** [comment]
Fixed in conda recipes.
